# Data Cleaning
Souhaïla El Filali

Created:       May 13, 2026

Last Updated:  May 14, 2026

### Importing libraries

In [16]:
import pandas as pd
import matplotlib.pyplot as plt

### Loding Dataset into DataFrame

In [17]:
df = pd.read_csv('../data/bronze/online_retail.csv') #  encoding='ISO-8859-1'
df.head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

### Inspecting Data Types

In [18]:
df.dtypes

index            int64
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

### Summarize Dataset

In [19]:
df.describe(include='all')

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.00000,541909,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,NaN,25900,4070,4223,NaN,23260,NaN,NaN,38
top,NaN,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,United Kingdom
freq,NaN,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,270954.00000,NaN,NaN,NaN,9.552250,NaN,4.611114,15287.690570,NaN
std,156435.79785,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN
min,0.00000,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN
25%,135477.00000,NaN,NaN,NaN,1.000000,NaN,1.250000,13953.000000,NaN
50%,270954.00000,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN
75%,406431.00000,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN
max,541908.00000,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN